export const GET__TRADE_HISTORY__LOADING = 'GET__TRADE_HISTORY__LOADING'
export const GET__TRADE_HISTORY__SUCCESS = 'GET__TRADE_HISTORY__SUCCESS'
export const GET__TRADE_HISTORY__ERROR = 'GET__TRADE_HISTORY__ERROR'

export const GET__TIKER__LOADING = 'GET__TIKER__LOADING'
export const GET__TIKER__SUCCESS = 'GET__TIKER__SUCCESS'
export const GET__TIKER__ERROR = 'GET__TIKER__ERROR'

